sudo: true
android:
  components:
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    
before_install:
  - chmod +x gradlew
  
install:
  - echo y | sdkmanager "ndk-bundle"
  
script:
  - ./gradlew assemble
  - ./gradlew test --info
